### PR TITLE
Adds ImportName, ImportAlias

### PR DESCRIPTION
**Pull request by dave**

### CODE REVIEW

**Comment by dave** [comment]
This fixes https://github.com/dave/jennifer/issues/32

**Comment by dave** [comment]
There's some rough edge cases I need to solve before merging this:

```
	f := NewFile("main")

	// package a should use name "a"
	f.ImportName("github.com/foo/a", "a")

	f.Func().Id("main").Params().Block(
		Qual("github.com/bar/a", "Bar").Call(),
		Qual("github.com/foo/a", "Foo").Call(),
	)
	fmt.Printf("%#v", f)

	// Output:
	// package main
	//
	// import (
	// 	a "github.com/bar/a"
	// 	"github.com/foo/a"
	// )
	//
	// func main() {
	// 	a.Bar()
	// 	a.Foo()
	// }
```

**Comment by dave** [comment]
I've solved this problem by ensuing all the names are unique (even the names provided by `ImportName` and `ImportAlias`). The names are registered during the render, which has the unfortunate side-effect that if something registers the name you requested earlier in the render, your name won't be available and it'll be aliased... Like this:

```
f := NewFile("main")

// We provide a hint that package foo/a should use name "a", but because package bar/a already
// registers the required name, foo/a is aliased.
f.ImportName("github.com/foo/a", "a")

f.Func().Id("main").Params().Block(
	Qual("github.com/bar/a", "Bar").Call(),
	Qual("github.com/foo/a", "Foo").Call(),
)
fmt.Printf("%#v", f)

// Output:
// package main
//
// import (
// 	a "github.com/bar/a"
// 	a1 "github.com/foo/a"
// )
//
// func main() {
// 	a.Bar()
// 	a1.Foo()
// }
```

In an ideal world, I'd do the render as two phases. One that registers all the names specifically requested by ImportName and ImportAlias that are used in the source. The second pass would register the automatically generated names and write the source. However this would make the whole project much more complex... and I think this is a minor edge case that you can get around by supplying non-conflicting aliases. 

I'm still going to think about tweaks to solve this.

**Comment by dave** [comment]
One question: In a large codebase where I'm generating lots of files, I would thing I might want to define the names of packages in one place, probably as a map. Would it be helpful if `ImportName` took a map instead? So:

```go
// packageNames might be defined once and used with several jen.Files 
packageNames := map[string]string{
	"github.com/foo/a": "a",
	"github.com/bar/b": "b",
	"github.com/baz/c": "c",
}

f := NewFile("main")

f.ImportNames(packageNames)

f.Func().Id("main").Params().Block(
	Qual("github.com/foo/a", "Foo").Call(),
)
fmt.Printf("%#v", f)

// Output:
// package main
//
// import (
// 	"github.com/foo/a"
// )
//
// func main() {
// 	a.Foo()
// }
```

**Comment by bruth** [comment]
@dave This looks great.

> One question: In a large codebase where I'm generating lots of files, I would thing I might want to define the names of packages in one place, probably as a map. Would it be helpful if ImportName took a map instead?

Yes that is a good point.. that would be useful in that case, but I also assume preferred named imports are usually all known up front rather than incrementally while writing the code.

**Comment by dave** [comment]
OK I've added `ImportNames`.

I've also exposed a `gennames` command that you can use to automatically generate an index of package names. I don't think this will be particularly useful in most use cases, but I had to write this to generate the index of standard library package names, so I thought I might as will make it available. It might be useful if you're vendoring all the packages you're going to import...

**Pull request merged**
