### PR TITLE
Add Header function for adding header comments

### PR DESCRIPTION
**Pull request by joshdk**
There are times when you want to add content like `// Code generated by...DO NOT EDIT.` or `MIT License - Copyright...` to the top of a generated file for semantic purposes.

You could use `File.PackageComment`, but then those comments show up in the Godoc, which isn't always desirable.

The following code:

```go
f := NewFile("example")
f.Header("Code generated by...")
f.PackageComment("Package example implements...")
f.Func().Id("init").Params().Block()
fmt.Printf("%#v", f)
```

Would generate the output:

```
// Code generated by...

// Package example implements...
// package example

func init() {}
```

Cheers!

### CODE REVIEW

**Comment by dave** [comment]
This is great! Thanks. I'd like a couple of changes:

1) I'd prefer the public method name to be `HeaderComment`. The naming of all the private fields is fine.

2) The doc comment should include a note about the extra line space: "HeaderComment adds a comment to the top of the file, above any package comments. A blank line is rendered below the header comments, ensuring header comments are not included in the package doc."

3) The examples can be merged - something like:

```
func ExampleFile_PackageComment() {
	f := NewFile("c")
	f.HeaderComment("header comment 1")
	f.HeaderComment("header comment 2")
	f.PackageComment("package comment 1")
	f.PackageComment("package comment 2")
	f.Func().Id("init").Params().Block()
	fmt.Printf("%#v", f)
	// Output:
	// // header comment 1
	// // header comment 2
        //
	// // package comment 1
	// // package comment 2
	// package c
	//
	// func init() {}
}
```

4) I'd prefer a single section in the readme:

```
### Comments
{{ "File.PackageComment" | doc }} 

{{ "File.HeaderComment" | doc }}

{{ "ExampleFile_PackageComment" | example }}
```

**Comment by dave** [comment]
Actually, let's make the example a bit more real-world:

f.Header("Code generated by...")
f.PackageComment("Package example implements...")

```go
func ExampleFile_PackageComment() {
	f := NewFile("c")
	f.HeaderComment("Code generated by...")
	f.PackageComment("Package c implements...")
	f.Func().Id("init").Params().Block()
	fmt.Printf("%#v", f)
	// Output:
	// // Code generated by...
        //
	// // Package c implements...
	// package c
	//
	// func init() {}
}
```

**Comment by joshdk** [comment]
Thank you for the feedback! I think I addressed your concerns outlined above. Please take another look and let me know that you think.

Also, that go generate/readme template/example test output setup is super clever!

**Comment by dave** [comment]
Great - just one last change: I'd like PackageComment to be first in the readme, because I think that's the one people will use most.

**Comment by dave** [comment]
>Also, that go generate/readme template/example test output setup is super clever!

Yeah it's great huh?

You might be interested in this: I recently added the `literals` feature to the becca tool ([used like this](https://github.com/dave/blast/blob/4a4bc831d5e5f4dea51cf3c48ba3d06fd8d6f0cc/main.go#L5)) that bundles up all the doc comments into a file like [this](https://github.com/dave/blast/blob/4a4bc831d5e5f4dea51cf3c48ba3d06fd8d6f0cc/blaster/doc-gen.go)... You can then use them in the helpers for [flags like this](https://github.com/dave/blast/blob/4a4bc831d5e5f4dea51cf3c48ba3d06fd8d6f0cc/blaster/config.go#L105-L119).

**Comment by dave** [comment]
It's ok I did the readme reorder. Thanks very much for the PR - much appreciated!

**Pull request merged**
