### PR TITLE
Support not formatting generated file.

### PR DESCRIPTION
**Pull request by pekim**
This is a possible solution for https://github.com/dave/jennifer/issues/59.

### CODE REVIEW

**Comment by dave** [comment]
I’m taking a break from open source and trekking across Nepal for five months... today is the first internet I’ve had in over a month. I won’t have my laptop until September but I’ll take a look at this when I can.

However from looking at your issue it looks like something I’ll merge with minimal changes... however without my laptop im not keen on hitting the merge button without some quick testing... hopefully you can use your forked version until I get back to civilisation in September?

p.s. if you want to know more about the trek, check out my blog wildernessprime.com :)

**Comment by pekim** [comment]
Thank you for taking a look. It's not a problem to continue to use my forked version for now.

Good luck with the rest of your trek.

**Review by spatecon — APPROVED** [review]
LGTM

**Comment by dave** [comment]
Sorry about the delay! Merged and tagged v1.6.0

**Pull request merged**
